[project]
name = "blocky-code-challenge"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
    "pytest>=8.3.4",
    "python-ta>=2.9.2",
]
